name: Deploy ContactPage

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            mkdir -p ~/contactpage
            cd ~/contactpage

            REPO_URL="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/NoNo47400/Contact_Website.git"
            if [ ! -d ".git" ]; then
              echo "First installation..."
              git clone $REPO_URL .
            else
              echo "Updating existing code..."
              git remote set-url origin $REPO_URL
              git pull
            fi

            cd frontend

            docker-compose down || true
            docker-compose up -d --build
